---
exp_todos: >-
  {{ [{'id': 5, 'title': 'pay invoices', 'doneStatus': false, 'description': ''},
      {'id': 8, 'title': 'schedule meeting', 'doneStatus': false, 'description': ''},
      {'id': 2, 'title': 'file paperwork', 'doneStatus': false, 'description': ''},
      {'id': 9, 'title': 'tidy meeting room', 'doneStatus': false, 'description': ''},
      {'id': 7, 'title': 'train staff', 'doneStatus': false, 'description': ''},
      {'id': 10, 'title': 'install webcam', 'doneStatus': false, 'description': ''},
      {'id': 1, 'title': 'scan paperwork', 'doneStatus': false, 'description': ''},
      {'id': 3, 'title': 'process payments', 'doneStatus': false, 'description': ''},
      {'id': 4, 'title': 'escalate late payments', 'doneStatus': false, 'description': ''},
      {'id': 6, 'title': 'process payroll', 'doneStatus': false, 'description': ''}] }}

desc200: >-
  This description has just enough characters to validate because it is exactly
  200 characters in length. I had to use a tool to check this - so I should have
  used a CounterString to be absolutely sure.

max_todo:
  title: this title has just enough characters to validate.
  doneStatus: true
  description: "{{ desc200 }}"

new_title: updated title

exp_opts: "{{ ['OPTIONS', 'GET', 'HEAD', 'POST'] }}"

exp_xml: |-
  <todos>
  <todo><doneStatus>true</doneStatus><description>{{ desc200 }}</description><id>15</id><title>{{ new_title }}</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>5</id><title>pay invoices</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>6</id><title>process payroll</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>1</id><title>scan paperwork</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>2</id><title>file paperwork</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>4</id><title>escalate late payments</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>9</id><title>tidy meeting room</title></todo>
  <todo><doneStatus>true</doneStatus><description/><id>11</id><title>create todo process payroll</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>7</id><title>train staff</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>10</id><title>install webcam</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>3</id><title>process payments</title></todo>
  <todo><doneStatus>false</doneStatus><description/><id>8</id><title>schedule meeting</title></todo></todos>

exp_todo_19: '{{ {"id": 3,
                  "title": "updated title",
                  "doneStatus": false,
                  "description": "updated description"} }}'

exp_todo_20: '{{ {"id": 3,
                  "title": "partial update for title",
                  "doneStatus": false,
                  "description": ""} }}'

exp_todo_21: '{{ {"errorMessages": ["title : field is mandatory"]} }}'
